set -g mouse on
set-option -g focus-events on

set-option -ag terminal-features 'xterm-256color'
set -ag terminal-overrides ",xterm-256color:Tc"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin "arcticicestudio/nord-tmux"

set -g status-interval 1
set -g status-position bottom
set -g status-left '[#S] '

run '~/.tmux/plugins/tpm/tpm'
